# Generated by Django 2.0.4 on 2018-04-17 23:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(128)])),
                ('y', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(128)])),
                ('is_mine', models.BooleanField(db_index=True, default=False)),
                ('revealed', models.BooleanField(default=False)),
                ('neighbors_mines', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('won', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(128)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(128)])),
                ('mines', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(8192)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.Game'),
        ),
    ]
